### ISSUE TITLE
Document minimum python version

### ISSUE THREAD

**Issue by jpburstrom** [madskjeldgaard/faust2sc.py#4]
While trying to get this to work, I found my python version was outdated. Apparently python 3.8 is needed for the shutil.copytree commands to work (more specifically the dirs_exist_ok argument). 

So a fix would be to either document that python 3.8 is needed, or make a workaround to support older versions. Here's a discussion about how to work around this  pre-3.8 limitation of copytree: https://stackoverflow.com/questions/1868714/how-do-i-copy-an-entire-directory-of-files-into-an-existing-directory-using-pyth

**Comment by madskjeldgaard** [comment]
Thanks for the headsup! 

Which of the solutions do you suggest we go for? I'm open for making it more backwards compatible - the important thing though is that we create a solution that will include something like the `dir_exists`  option in shutils.

python 3.8 is more than two years old now but perhaps older systems like Debian etc have far older versions of python installed.

**Comment by jpburstrom** [comment]
It seems current Debian stable is using python 3.9, so no problem there. I'm on MacOS where python is a mess (or at least I never really understood how it works) - but it seems homebrew has versions from 3.8 up to 3.10. So I don't know if backwards compatibility is a problem, really. In any case, the hard part is probably to figure out what version of python to support.

So given that, maybe just document it and fix it if the need should arise?

**Comment by jpburstrom** [comment]
And I see you've already commented on that in the README, so I'm closing this for now. Thanks!
