### ISSUE TITLE
Audio input missing from class file

### ISSUE THREAD

**Issue by jpburstrom** [madskjeldgaard/faust2sc.py#5]
I'm not sure if this is me doing something wrong, but I can't get the generated class files to include the inputs to the faust process. The faust file below generates *ar/*kr-methods with only one argument, `cutoff`. The faust2supercollider script from the faust distribution prepends an in1 argument. What can be the problem here?

Faust file:
```
import("stdfaust.lib");
freq=vslider("cutoff",500,20.0,20000,1);
process= _: ve.wah4(freq) : _;
```

Generated class file:
```
Wah4 : UGen {
    *ar{|cutoff(500)| 
      ^this.multiNew('audio', cutoff)
    }

    *kr{|cutoff(500)|
      ^this.multiNew('control', cutoff)
    }
...
}
```

**Comment by madskjeldgaard** [comment]
Oh sorry, this is a bug I just introduced I see now. Let me fix it really quikc

**Comment by madskjeldgaard** [comment]
Should be fixed now. Thanks for the issue!
